name: 'Set environment variables'
description: 'Configures environment variables for a workflow'
inputs:
  varFilePath:
    description: 'File path to variable file or directory. Defaults to ./.github/variables/* if none specified and runs against each file in that directory.'
    required: false
    default: ./.github/variables/*
runs:
  using: "composite"
  steps:
    - shell: bash
      name: Echo Env
      run: |
        echo "exportPath: $exportPath"
    - shell: bash
      run: |
        sed "" ${{ inputs.varFilePath }} >> $GITHUB_ENV
        echo "exportPath=Modified" >> $GITHUB_ENV
      
