name: Call reusable workflow

on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/reusable-workflow-2.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
