name: Call reusable workflow

on:
  workflow_dispatch:

jobs:
  job2:
    uses: ./.github/workflows/reusable-workflow-2.yml

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: echo ${{ needs.job2.outputs.firstword }} ${{ needs.job2.outputs.secondword }}
