name: Call reusable 3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [DEVOPS]
    # runs-on: ubuntu-latest
    steps:
      - name: Run Info
        run: |
          echo "Run Id: ${{ github.run_id }}"
          echo "Run Number: ${{github.run_number}}"
          echo "Branch: ${{github.ref}}"
          echo "running on branch ${GITHUB_REF}"
      - name: Create Change Log For Manual Dispatch
        run: |
           date > changelog.txt
           echo "Run Id: ${{ github.run_id }}"
           echo "Run Number: ${{github.run_number}}"
      - name: Upload changes
        uses: actions/upload-artifact@v3
        with:
          name: changes
          path: changelog.txt  
      - name: Remove Current Change Log
        run: |
           rm changelog.txt          
      - name: Download Recent Successful Commit
        env:
          changeLog: changes.txt
          scheme: 'Marriott (TST)'
          config: Integration      
        uses: dawidd6/action-download-artifact@v2
        with:
          name: changes
          github_token: ${{github.token}}
          workflow: call2.yml
          workflow_conclusion: in_progress
          check_artifacts: true
          search_artifacts: true                    
      - name: Trigger Workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "test.yml",
              ref: context.ref,
              inputs: {
                name: "Mo Fish",
                commit_source: context.actor,
                fusionid: "MITM"
              }
            })
  # job2:
  #   uses: ./.github/workflows/reusable-workflow-2.yml

  # job3:
  #   runs-on: ubuntu-latest
  #   needs: job2
  #   steps:
  #     - run: echo ${{ needs.job2.outputs.firstword }} ${{ needs.job2.outputs.secondword }}
