name: Call reusable 3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [DEVOPS]
    # runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'test.yml',
              ref: 'main',
              inputs: {
                name: 'Mo'
              }
            })
  # job2:
  #   uses: ./.github/workflows/reusable-workflow-2.yml

  # job3:
  #   runs-on: ubuntu-latest
  #   needs: job2
  #   steps:
  #     - run: echo ${{ needs.job2.outputs.firstword }} ${{ needs.job2.outputs.secondword }}
