name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
      use-emoji:
        type: boolean
        description: Include  emojis
      message:
        required: true        

jobs:
  greet:
    runs-on: [DEVOPS]

    steps:
      - name: Checkout
        uses: actions/checkout@v3    
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
        # Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
        # Required, if the artifact is from a different repo
        # Required, if the repo is private a Personal Access Token with `repo` scope is needed
         github_token: ${{secrets.GITHUB_TOKEN}}
         # Optional, workflow file name or ID
         # If not specified, will be inferred from run_id (if run_id is specified), or will be the current workflow
         workflow: composite-workflow.yml
         name: timestamp
      - name: Extract Last Run Time
        run: |
          lastRun=$(cat timestamp.txt)
          echo "Last Run: $lastRun"
          #ls -R             
      - shell: bash
        name: "Set Base Env"
        run: |
          hostname -s
          echo "exportPath=$HOME/build/INT" >> $GITHUB_ENV    
          date > timestamp.txt
      - name: Set Environment Variables
        uses: tw3lveparsecs/github-actions-setvars@latest
        with:
         envFilePath: ./.github/variables/myvars.env
#      - uses: actions/checkout@v3         
#      - name: Set Environment Variables
#        uses: ./.github/actions/setvars
#        with:
#          varFilePath: ./.github/variables/myvars.env   
      - name: Upload Time Stamp
        #if: ${{ false }}
        uses: actions/upload-artifact@v2
        with:
          name: timestamp
          path: timestamp.txt
      - name: Send greeting
        run: |
          echo "Test"
          echo "MYVAR1: $MYVAR1"
          echo "exportPath: $exportPath"
          #echo  The tags are ${{ inputs.tags }}        
          echo "Message: ${{ github.event.inputs.message }}" 
          echo "Use Emoji: ${{ github.event.inputs.use-emoji }}"
          $echo ${{ fromJSON('["", ""]')[github.event.inputs.use-emoji == 'true'] }} 
          echo "Choice: ${{ github.event.inputs.name }}"
