name: Mixed inputs

on:
  workflow_dispatch:
    inputs:
      name:
        type: choice
        description: Who to greet
        options: 
        - monalisa
        - cschleiden
      use-emoji:
        type: boolean
        description: Include  emojis
      message:
        required: true        

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
    - name: Send greeting
      run: |
        echo "Test"
        echo  The tags are ${{ inputs.tags }}        
        echo "Message: ${{ github.event.inputs.message }}" 
        echo "${{ github.event.inputs.use-emoji }}"
        $echo ${{ fromJSON('["", ""]')[github.event.inputs.use-emoji == 'true'] }} 
        echo "${{ github.event.inputs.name }}"
