# This is a basic workflow that is manually triggered

name: Parsing workflow

# or API.
on:
  workflow_dispatch:

jobs:
  parse:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    - name: Parse Stuff
      run: |
        echo "Workflow to parse stuff..."
        var=${{secrets.APPCENTER_TOKEN}}
        varlen=${#var}
        echo "Len: $varlen"
        echo $var | cut -c2-$varlen  
        echo $var | cut -c1-1
        echo "==================================="
        echo "==================================="
        var=${{secrets.APPDOME_REGRESSION_FUSION_SET}}
        varlen=${#var}
        echo "Len: $varlen"
        echo $var | cut -c2-$varlen  
        echo $var | cut -c1-1
        echo "==================================="
        echo "==================================="
        var=${{secrets.APPDOME_REGRESSION_TEAM_ID}}
        varlen=${#var}
        echo "Len: $varlen"
        echo $var | cut -c2-$varlen  
        echo $var | cut -c1-1
        echo "==================================="
        echo "==================================="
        var=${{secrets.APPDOME_TOKEN}}
        varlen=${#var}
        echo "Len: $varlen"
        echo $var | cut -c2-$varlen  
        echo $var | cut -c1-1
        echo "==================================="
        echo "==================================="
        var=${{secrets.LE_ALIAS_PASSWORD}}
        varlen=${#var}
        echo "Len: $varlen"
        echo $var | cut -c2-$varlen  
        echo $var | cut -c1-1
        echo "==================================="
        echo "==================================="
        var=${{secrets.LE_KEYSTORE_ALIAS}}
        varlen=${#var}
        echo "Len: $varlen"
        echo $var | cut -c2-$varlen  
        echo $var | cut -c1-1
        echo "==================================="
        echo "==================================="
        var=${{secrets.LE_KEYSTORE_PASSWORD}}
        varlen=${#var}
        echo "Len: $varlen"
        echo $var | cut -c2-$varlen  
        echo $var | cut -c1-1
        echo "==================================="
        echo "==================================="
        var=${{secrets.LOWER_ENV_KEYSTORE}}
        varlen=${#var}
        echo "Len: $varlen"
        echo $var | cut -c2-$varlen  
        echo $var | cut -c1-1
