name: Every 5 minutes
on:
  schedule:
    - cron: '1/5 * * * *'
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually
    inputs:
      text_to_print:
        description: 'What text do you want to print?'
#         required: true
#         default: 'Periodically printing passages'

jobs:
  print_text:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Set the variables
        env:
          github.event.inputs.text_to_print: "WTF"
          text_to_printDefault: 'Default Message' # here is the default message
        run: echo "text_to_print=${{ github.event.inputs.text_to_print || env.text_to_printDefault }}" >> $GITHUB_ENV

      - name: Print some text
        run: echo "$text_to_print" # prints the environmental variable, MESSAGE
