name: Every 3rd minute
on:
  schedule:
    - cron: '1/3 * * * *'
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually
    inputs:
      text_to_print:
        description: 'What text do you want to print?'
        required: true
        default: 'Periodically printing passages'

jobs:
  print_text:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Set the variables
        env:
          github.event.inputs.text_to_print: "WTF"
          dsap: "${{ github.event.inputs.text_to_print || 'The default value to use' }}"
          DEFAULT_MESSAGE: 'Default Message' # here is the default message
        run: echo "text_to_print=${{ github.event.inputs.text_to_print || 'The default value to use' }}" >> $GITHUB_ENV

      - name: Print some text
        run: |
          echo "$text_to_print" # prints the environmental variable, MESSAGE
          echo "DSAP: ${dsap}"
