name: Every 3rd minute
on:
  #schedule:
  #  - cron: '1/3 * * * *'
  workflow_dispatch: # adding the workflow_dispatch so it can be triggered manually
#    inputs:
#      dsap:
#        description: 'DSAP Environment(tst1/tst2/uat1/uat2)'
#         required: true
#        default: 'tst1'

jobs:
  setup:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: DSAP uat1
        if: ${{ env.dsap == 'uat1' }}
        run: |
          echo "DSAP_URL=gatewaydsapuat1.marriott.com" >> $GITHUB_ENV  
  job2:
    uses: ./.github/workflows/reusable-workflow-2.yml
    with:
      word_uno: "${DSAP_URL}"
    
  print_text:
    runs-on: 'ubuntu-20.04'
    steps:
      - name: Set the variables
        env:
          test: "WTF"
          #dsap: >            "${{ github.event.inputs.text_to_print || 'The default value to use' }}"
        run: |
           echo "Build number: ${{github.run_number}}"
           echo "dsap=${{ github.event.inputs.dsap || 'uat1' }}" >> $GITHUB_ENV
           
      - name: DSAP uat1
        if: ${{ env.dsap == 'uat1' }}
        run: |
          echo "DSAP_URL=gatewaydsapuat1.marriott.com" >> $GITHUB_ENV
          
      - name: Print some text
        run: |
          echo "DSAP: ${dsap}"
          echo "DSAP: ${{env.dsap}}"
          echo "DSAP URL: ${DSAP_URL}"
