# This is a basic workflow that is manually triggered

name: Test

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Person to greet'
        # Default value if no value is explicitly provided
        default: 'World'
        # Input has to be provided for the workflow to run
        required: true
        # The data type of the input
      #   type: string
      commit_source:
        description: Run Id of commit hash source
      fusionid:
        type: choice
        description: Fusion Set
        options:
        - ""
        - "MITM"
        - "No MITM"
        default: "No MITM" 
      cancelable:
        type: boolean
        default: 'false'
        description: 'Cancel job if no changes detected'
      attach_commit_hash:
        type: boolean
        default: 'true'
        description: 'Attach commit hash to run'
      upload_to_app_center:
        type: boolean
        default: 'true'
        description: 'Upload ipa to App Center'        

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: [DEVOPS]
    # runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Download Recent Successful Commit
      uses: dawidd6/action-download-artifact@v2
      with:
          name: changes
          github_token: ${{github.token}}
          workflow: call2.yml
          check_artifacts: true
          search_artifacts: true          

    - name: Process Last Commit Hash Info
      run: |
        ls -lah
    - name: Send greeting
      run: |
        echo "Commit Hash Source: ${{ inputs.commit_source }}"
        echo "Hello ${{ inputs.name }}"
        echo "fusionid: ${{ inputs.fusionid }}"
        echo "Build number: ${{github.run_number}}"
        echo "Branch: ${{github.ref}}"
        echo "Is Cancelable: ${{ inputs.cancelable }}"
        echo "Event Name: ${{github.event_name}}"
